services:
  big-deposits-local:
    image: big-deposits
    volumes:
      - ../../source/big-deposits/configDocker:/app/configDocker:ro
      - ../../source/big-deposits/dataDocker:/app/dataDocker:rw
    restart: "no"

