services:
  diff-prices-local:
    image: diff-prices
    volumes:
      - ../../source/diff-prices/configDocker:/app/configDocker:ro
      - ../../source/diff-prices/dataDocker:/app/dataDocker:rw
    restart: "no"

