services:
  diff-prices:
    image: softfx/tt-reporting:latest-diff-prices
    pull_policy: always
    volumes:
      - ./configDockerExample:/app/configDocker:ro
      - ./dataDockerExample:/app/dataDocker:rw
    restart: "no"
  diff-prices-local:
    image: diff-prices
    volumes:
      - ../../source/diff-prices/configDocker:/app/configDocker:ro
      - ../../source/diff-prices/dataDocker:/app/dataDocker:rw
    restart: "no"

