services:
  negative-equity-local:
    image: negative-equity
    volumes:
      - ../../source/negative-equity/configDocker:/app/configDocker:ro
      - ../../source/negative-equity/dataDocker:/app/dataDocker:rw
    restart: "no"

