services:
  count-trades-local:
    image: count-trades
    volumes:
      - ../../source/count-trades/configDocker:/app/configDocker:ro
      - ../../source/count-trades/dataDocker:/app/dataDocker:rw
    restart: "no"

