services:
  big-trades-local:
    image: big-trades
    volumes:
      - ../../source/big-trades/configDocker:/app/configDocker:ro
      - ../../source/big-trades/dataDocker:/app/dataDocker:rw
    restart: "no"

